
object Versions {

    const val coreKtx = "1.10.1"
    const val appcompat = "1.6.1"
    const val annotation = "1.7.0"
    const val material = "1.11.0"
//    const val constraintlayout = "2.1.4"
    const val kotlinVersion = "2.0.0"
    const val hiltVersion = "2.46"
    const val gradleVersion = "8.1.1"
//    const val lifecycle = "2.5.1"
//    const val room = "2.6.1"
//    const val rxbinding = "4.0.0"
//    const val glide = "4.11.0"
//    const val window ="1.0.0"
//    const val orbit ="6.0.0"
    const val compose = "1.6.8"
    const val junit = "4.13.2"
    const val junitVersion = "1.1.5"
    const val espressoCore = "3.5.1"
    const val lifecycleRuntimeKtx = "2.6.1"
    const val activityCompose = "1.8.0"
    const val composeBom = "2024.04.01"
}